### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by GustavoCostaW** [purplecabbage/phonegap-plugin-sidebar#7]
1 - Allow draggable gesture to open sidebar

Improvements in methods:

1 - Customization when create sidebar set background color, font color, and width of sidebar
2 - Add the options, addItems([['id?','title','image','item-caption'],...])
3 - addItem(item)
4 - removeAllItems()
5 - removeItem(id)
6 - blockDrag();
7 - allowDrag();

**Comment by purplecabbage** [comment]
1. is covered in the other improvements.

I'll add individual issues for addItem/removeItem/removeAll and allow/block dragging
